# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01afa1ce6b156a1c09c17f407ab703f04fd253c40d2c9ad4bada29c9a58d886a7fe31118b792968299754f81067b0f12f751d0679cdede77793eee7268cdb3ab

test:
  secret_key_base: 61885d15f503a8d334e137601bab842bb5c42e6b219d1d8105187394c5c8cdd0d12e5ce851a91ea1f06d24a58f3e7b812b8ee37524101a9052e80cf33a151d2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 56565656565656spq
